### ISSUE TITLE
Noarch build should be marked as broken

### ISSUE THREAD

**Issue by haasad** [conda-forge/bw2calc-feedstock#6]
### Comment:

Currently the noarch build takes precedence over all the other builds (even though they have a higher build number). E.g. when installing on linux:
```
conda create -n abc --dry-run -c conda-forge brightway2 | grep bw2calc
  bw2calc            conda-forge/noarch::bw2calc-1.8.1-pyhd8ed1ab_0
```
But it also happens on windows and osx -> https://github.com/haasad/activity-browser/actions/runs/3669758199/jobs/6203822495

This means that there is currently no solver library installed when installing brightway, which is a bad user experience and makes tools like the activity-browser borderline unusable. I think the "easiest" way to fix i would be to request the noarch to be marked as broken: https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages
I assume a maintainer of the feedstock has to do this.

Otherwise bw2calc could be bumped to `1.8.2`, where there won't be a noarch package anymore.

@m-rossi, @cmutel

**Comment by m-rossi** [comment]
You are right @haasad we should mark it as broken. I will take care of that.

**Comment by haasad** [comment]
```
conda create -n abc --dry-run -c conda-forge brightway2 | grep bw2calc
  bw2calc            conda-forge/linux-64::bw2calc-1.8.1-py311h38be061_3 
```
Works, thx :+1:
